name: Deploy to Amazon ECS

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check out code
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ vars.AWS_REGION }}

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

     - name: Cache Docker layers
       uses: actions/cache@v4
       with:
         path: /tmp/.buildx-cache
         key: ${{ runner.os }}-buildx-${{ github.sha }}
         restore-keys: |
           ${{ runner.os }}-buildx-

     - name: Log in to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2

     - name: Build Docker image
       run: |
         docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .

     - name: Push Docker image to ECR
       run: |
         docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

     - name: Install dependencies
       run: |
         # Install jq for JSON processing
         sudo apt-get update && sudo apt-get install -y jq
         # Install ecs-deploy script
         curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
         sudo chmod +x /usr/bin/ecs-deploy

     - name: Update ECS task definition
       run: |
         # Retrieve current task definition
         aws ecs describe-task-definition \
           --task-definition ${{ secrets.AWS_TASK_DEFINITION_NAME }}:1 \
           | jq '.taskDefinition | del(
             .taskDefinitionArn, 
             .revision, 
             .status, 
             .requiresAttributes, 
             .compatibilities, 
             .registeredAt, 
             .registeredBy
           )' > current-task-definition.json
         
         # Update the container image in the task definition
         NEW_IMAGE="${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}"
         jq --arg IMAGE "$NEW_IMAGE" '.containerDefinitions[0].image = $IMAGE' current-task-definition.json > updated-task-definition.json
         
         # Register the updated task definition
         aws ecs register-task-definition --cli-input-json file://updated-task-definition.json

     - name: Deploy to ECS using ecs-deploy
       run: |
         ecs-deploy \
         --cluster ${{ secrets.ECS_CLUSTER }} \
         --service-name ${{ secrets.ECS_SERVICE_NAME }} \
         --image ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} \
         --task-definition ${{ secrets.AWS_TASK_DEFINITION_NAME }}:$LATEST_TASK_REVISION \
         --force-new-deployment
